### ISSUE TITLE
Never finish loading... quick edit form

### ISSUE THREAD

**Issue by vernetmatias** [carfup/PCFControls#126] opened 2021-08-04 19:10 UTC
Hello Clement,
When I create a record using Flow and then open the record, the control doesn't loads at the first time I open it but if i close and then open again then it loads properly, 
here is a print screen it stays like that:
![image](https://user-images.githubusercontent.com/36961292/128240270-ee4eafce-cdef-425c-a20d-f0f070d740e4.png)

then when i go out from the form and reopen it, it loads:
![image](https://user-images.githubusercontent.com/36961292/128240596-89376a6a-b951-48e7-8e98-53d53dbc4164.png)

**Comment by carfup** [comment] 2021-08-05 18:42
Hello,
Thanks for your feedback, I have to try to reproduce the issue here.
Quick one, does it occurs when you create a record from the dynamics UI too ?
If you have knowledge about the developer tool of your browser, can you check and let me know if there are critical errors displayed ?

**Comment by vernetmatias** [comment] 2021-08-06 13:30
ok, here is the file with the errors: yes, there are a few, some are maybe mine but another could be something to do with the control...
[editQuickViewErrorLoading.txt](https://github.com/carfup/PCFControls/files/6945812/editQuickViewErrorLoading.txt)

**Comment by vernetmatias** [comment] 2021-08-06 15:42
no, the lookup field name is "axx_persona", it is a relationship with accounts, here it is an image, and when I reload the form then it loads correctly, and all the errors disapear, here the log from the page when it loads correctly:
[editQuickViewCorrectLoading.txt](https://github.com/carfup/PCFControls/files/6946540/editQuickViewCorrectLoading.txt)
![image](https://user-images.githubusercontent.com/36961292/128535799-57bcd8b0-3053-4764-a6f9-ed8e03ca818c.png)

**Comment by vernetmatias** [comment] 2021-08-10 15:04
Hello Clement, any idea?, i think it's a bug, from the control itself, maybe generated because the form loads to much things and it can't finish loading or tries to get data when the form doesn't finish loading, I don.t know... the field "'axx_idrector". Is the field that loads in the quick view form, the first one you see there "ID. Rector". But if I put another field first on the form it changes the field giving the error, always asuming that the first one is undefined, here a screenshot:
![image](https://user-images.githubusercontent.com/36961292/128891272-f2622ecd-1a03-41c5-b1ab-7b0391e5b8c6.png)

**Comment by vernetmatias** [comment] 2021-08-23 16:07
Hello Clement, how are you doing?, Do you know what this could be? I wnat to know because if i don't resolve it I won't be able to use your control and it seems to be a small bug maybe. Thanks!!

**Comment by carfup** [comment] 2021-08-31 07:18
Hi,
First, sorry for the late reply, I was off without internet ...
Thanks for the report, I have to dig this as it seems really critical.
Problem is that I'm not able to reproduce the issue you are the first two to report it.
Any chance you could share an access to a MdA which is having the issue ? 

@radevic I'll check your two approaches and get back to you.

I have to push a new release soon since I also adjusted the PCF to be bind on a lookup field so :).

Regards,

**Comment by carfup** [comment] 2021-08-31 13:21
Model Driven App =).
Sure thing, if you don't mind giving me a dummy user just to reproduce the issue this would be perfect.
You can reach me in private on LinkedIn if it's fine for you : https://www.linkedin.com/in/clemolivier/

**Comment by carfup** [comment] 2021-09-06 15:49
as follow up, @radevic you were right, about the approach.
funny thing is locally I fixed the issue before Matias reported it but I found out about this another way.
This will be fixed with the next release which should be pushed in the next few days !

**Comment by radevic** [comment] 2021-09-07 11:04
Good to hear that @carfup , looking forward to see the next release, thanks :)

**Comment by carfup** [comment] 2021-09-07 12:32
The release 1.4.0.0 is available to fix this : https://github.com/carfup/PCFControls/releases/tag/1.4.0.0

**Closed by carfup** 2021-09-07 12:32 UTC
Labels: Quick Edit Form, Part of next release
